[package]
name = "plua"
version = "0.1.1"
edition = "2024"
authors = ["Corey Schram <coreyschram@gmail.com>"]
license = "MIT"
description = "Lua preprocessor inspired by Nelua"
homepage = "https://github.com/cschram/plua"
repository = "https://github.com/cschram/plua"
readme = "README.md"
keywords = ["lua", "preprocessor"]

[lib]
name = "plua"
path = "src/lib.rs"

[[bin]]
name = "plua"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
glob = "0.3.2"
log = "0.4.26"
mlua = { version = "0.10.3", features = ["lua54", "vendored", "anyhow"] }
pest = "2.7.15"
pest_derive = "2.7.15"
pretty_env_logger = "0.5.0"
stylua = { version = "2.0.2", features = ["lua54"] }
