Program = _{ SOI ~ (Line ~ EOL)* ~ (Line ~ EOI) }

Line = _{
	Comment
  | MetaInclude
  | MetaLine
  | LuaLine
}

Comment = _{ "--" ~ Character* }

// Meta includes:
// ```
// ##!include "myinclude"
// ```
MetaInclude = { MetaIncludePrefix ~ DoubleQuote ~ Filename ~ DoubleQuote ~ Whitespace* }

MetaIncludePrefix = _{ Whitespace* ~ "##!include" ~ Whitespace* }

DoubleQuote = _{ "\"" }

Filename = { (!DoubleQuote ~ Character)+ }

// Preprocessor meta-code line
MetaLine = { MetaMultiLine | MetaSingleLine }

// Single-line preprocessor code:
// ```
// ## local foo = "bar"
// ```
MetaSingleLine = _{ MetaSingleLinePrefix ~ MetaSingleLineContent }

MetaSingleLinePrefix = _{ Whitespace* ~ "##" }

MetaSingleLineContent = { Character* }

// Multi-line preprocessor code:
// ```
// ##```
//   function foo()
//     return "foo"
//   end
// ```##
// ```
MetaMultiLine = _{ MetaMultiLinePrefix ~ MetaMultiLineContent ~ MetaMultiLineSuffix }

MetaMultiLinePrefix = _{ Whitespace* ~ "##```" }

MetaMultiLineSuffix = _{ "```##" }

MetaMultiLineContent = { (!(MetaMultiLinePrefix | MetaMultiLineSuffix) ~ ANY)* }

// Preprocessor value interpolation
// ```
// print(#[foo]#)
// ```
MetaValueInterpolate = { MetaValueInterpolatePrefix ~ Lua ~ MetaValueInterpolateSuffix }

MetaValueInterpolatePrefix = _{ "#[" }

MetaValueInterpolateSuffix = _{ "]#" }

// Preprocessor code interpolation
// ```
// ## function increment(ident, inc)
//   #{ident}# = #{ident}# + #[inc]#
// ## end
MetaCodeInterpolate = { MetaCodeInterpolatePrefix ~ Lua ~ MetaCodeInterpolateSuffix }

MetaCodeInterpolatePrefix = _{ "#{" }

MetaCodeInterpolateSuffix = _{ "}#" }

// Any lua code
LuaLine = { (MetaValueInterpolate | MetaCodeInterpolate | Lua)* }

Lua = { (!(MetaValueInterpolatePrefix | MetaValueInterpolateSuffix | MetaCodeInterpolatePrefix | MetaCodeInterpolateSuffix) ~ Character)+ }

// Common rules
EOL = _{ "\n" | "\r\n" }

Whitespace = _{ " " | "\t" }

Character = _{ !EOL ~ ANY }

